

services:
  backend:
    build: ./backend
    image: financial-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  frontend:
    build: ./frontend
    image: financial-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
